language: d
sudo: false

addons:
  mariadb: '10.1'
  apt:
    packages: [ libevent-dev ]

#install: ./travis-setup.sh
install: dmd -of=ci_setup ci_setup.d && ./ci-setup
script: ./run-tests

matrix:
  include:
    - d: dmd-2.080.0
      env: DUB_SELECT=vibe-0.8.3 # DMDFE 2.079+ doesn't support vibe.d v0.7.32
    - d: dmd-2.079.1
      env: USE_UNIT_THREADED=true DUB_SELECT=vibe-0.8.3
    - d: dmd-2.078.3
      env: USE_UNIT_THREADED=true
    - d: dmd-2.077.1
      env: USE_UNIT_THREADED=true
    - d: dmd-2.076.1
    - d: dmd-2.075.1
    - d: dmd-2.074.1
    - d: dmd-2.073.1
    - d: dmd-2.072.2
    - d: dmd-2.071.2
    - d: dmd-2.070.2
    - d: dmd-2.069.2
    - d: dmd-2.068.2
    - d: ldc-1.9.0
      env: DUB_SELECT=vibe-0.8.3 # DMDFE 2.079+ doesn't support vibe.d v0.7.32
    - d: ldc-1.8.0
      env: USE_UNIT_THREADED=true
    - d: ldc-1.7.0
      env: USE_UNIT_THREADED=true
    - d: ldc-1.6.0
      env: USE_UNIT_THREADED=true
    - d: ldc-1.5.0
    - d: ldc-1.4.0
    - d: ldc-1.3.0
    - d: ldc-1.2.0
    - d: ldc-1.1.1
    - d: ldc-1.0.0
    - d: ldc-0.17.5
    - d: ldc-0.17.1
    - d: ldc-0.17.0
    - d: gdc-6.3.0
    - d: gdc-4.8.5
    - d: dmd-beta
      env: DUB_SELECT=vibe-0.8.3 # DMDFE 2.079+ doesn't support vibe.d v0.7.32

    # Test alternative db versions, but only on one compiler version
    - d: dmd-2.078.3
      services:
        - mysql
      addons: # Remove "mariadb: ..." from default addons, but keep "libevent-dev"
        apt:
          packages: [ libevent-dev ]
      env: DB=mysql-default USE_UNIT_THREADED=true

    - d: dmd-2.078.3
      addons:
        mariadb: '5.5'
        apt:
          packages: [ libevent-dev ]
      env: DB=mariadb-5.5 USE_UNIT_THREADED=true

    - d: dmd-2.078.3
      addons:
        mariadb: '10.0'
        apt:
          packages: [ libevent-dev ]
      env: DB=mariadb-10.0 USE_UNIT_THREADED=true

    - d: dmd-2.078.3
      addons:
        mariadb: '10.2'
        apt:
          packages: [ libevent-dev ]
      env: DB=mariadb-10.2 USE_UNIT_THREADED=true

    - d: dmd-2.078.3
      addons:
        mariadb: '10.3'
        apt:
          packages: [ libevent-dev ]
      env: DB=mariadb-10.3 USE_UNIT_THREADED=true

    # on Mac just test latest & oldest supported dmd and ldc
    - d: dmd-2.080.0
      env: DUB_SELECT=vibe-0.8.3 # DMDFE 2.079+ doesn't support vibe.d v0.7.32
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: dmd-2.079.1
      env: DUB_SELECT=vibe-0.8.3 # DMDFE 2.079+ doesn't support vibe.d v0.7.32
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: dmd-2.078.3
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: ldc-1.9.0
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: ldc-1.8.0
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: dmd-2.068.2
      os: osx

    - d: ldc-0.17.0
      os: osx

    # Test with all dependencies updated
    # (dub.selections.json is deliberately kept old)
    - d: dmd-2.080.0
      services:
        - mysql
      env: DUB_UPGRADE=true DB=mysql-default

  allow_failures:
    # Doesn't appear to exist on travis: https://github.com/travis-ci/travis-ci/issues/8849
    - d: gdc-6.3.0

    # Occasional failures are expected here
    - d: dmd-beta
