language: d
sudo: false

addons:
  mariadb: '10.1'
  apt:
    packages: [ libevent-dev ]

matrix:
  include:
    - d: dmd-2.080.0
      env: DUB_SELECT=vibe-0.8.3 # DMDFE 2.079+ doesn't support vibe.d v0.7.32
    - d: dmd-2.079.1
      env: DUB_SELECT=vibe-0.8.3 # DMDFE 2.079+ doesn't support vibe.d v0.7.32
    - d: dmd-2.078.3
    - d: dmd-2.077.1
    - d: dmd-2.076.1
    - d: dmd-2.075.1
    - d: dmd-2.074.1
    - d: dmd-2.073.1
    - d: dmd-2.072.2
    - d: dmd-2.071.2
    - d: dmd-2.070.2
    - d: dmd-2.069.2
    - d: dmd-2.068.2
    - d: ldc-1.9.0
      env: DUB_SELECT=vibe-0.8.3 # DMDFE 2.079+ doesn't support vibe.d v0.7.32
    - d: ldc-1.8.0
    - d: ldc-1.7.0
    - d: ldc-1.6.0
    - d: ldc-1.5.0
    - d: ldc-1.4.0
    - d: ldc-1.3.0
    - d: ldc-1.2.0
    - d: ldc-1.1.1
    - d: ldc-1.0.0
    - d: ldc-0.17.5
    - d: ldc-0.17.1
    - d: ldc-0.17.0
    - d: gdc-6.3.0
    - d: gdc-4.8.5

    # Test alternative db versions, but only on one compiler version
    - d: dmd-2.070.2
      addons:
        mariadb: '5.5'
      env: DB=mariadb-5.5

    - d: dmd-2.070.2
      services:
        - mysql
      env: DB=mysql-default

    # on Mac just test latest & oldest supported dmd and ldc
    - d: dmd-2.080.0
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: dmd-2.079.1
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: dmd-2.078.3
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: ldc-1.9.0
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: ldc-1.8.0
      os: osx
      osx_image: xcode9 # use OSX 10.13

    - d: dmd-2.068.2
      os: osx

    - d: ldc-0.17.0
      os: osx

    # Test with all dependencies updated
    # (dub.selections.json is deliberately kept old)
    - d: dmd-2.080.0
      services:
        - mysql
      env: DUB_UPGRADE=true DB=mysql-default

  allow_failures:
    # Doesn't appear to exist on travis: https://github.com/travis-ci/travis-ci/issues/8849
    - d: gdc-6.3.0

    # Not working here, but vibe.d doesn't support DMD 2.080 yet anyway.
    # See: https://github.com/vibe-d/vibe.d/issues/2155
    - d: dmd-2.080.0
      os: osx

# MySQL is not installed by default on OSX build agents
before_install:
    - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
    - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install mysql && brew services start mysql; fi"

before_script:
    - mysql -u root -e 'SHOW VARIABLES LIKE "%version%";'
    - mysql -u root -e 'CREATE DATABASE mysqln_testdb;'
    - echo 'host=127.0.0.1;port=3306;user=root;pwd=;db=mysqln_testdb' > testConnectionStr.txt

install: ./travis-install-deps.sh
script: ./run-tests
